spring.application.name=shopeasy-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shopeasy
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=864657034473-g31oo1bqfqmd5rdkofqrpd3ivkn2fpbi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# Increase maximum file size (e.g., 200MB)
spring.servlet.multipart.max-file-size=200MB

# Increase maximum request size (e.g., 500MB total for multiple files)
spring.servlet.multipart.max-request-size=500MB
